### ISSUE TITLE
Make background black

### ISSUE THREAD

**Issue by lukassnoek** [janfreyberg/niwidgets#3]
Hi, cool widget you built! Perhaps the widget could improve by making the background black? At this moment, the background has the color of the color corresponding to 0 given a certain colormap. 

One idea is to use the `numpy.masked_where` function, like this:
`np.ma.masked_where(data == 0, data)` 

(Assuming that the background, i.e. voxels outside the brain, are coded zero.)

Should I submit a PR? If so, should this be the default, or accessible through a parameter upon initialization or upon called `nifti_plotter`?

**Comment by janfreyberg** [comment]
I think that's a good idea and would make the widget much neater 👍

How common is it to have values of exactly 0 inside the brain data? Would be a shame to have holes in the data, so maybe add a keyword argument like `mask_zeros=True`.

Would be great if you submit a pr, otherwise I'll get to it when I get home from amsterdam :)

**Comment by janfreyberg** [comment]
Just updated the widget to do this.

There's a new keyword argument called `mask_background`, which by default is `True`. When `True`, this makes the widget mask all values which are roughly zero (exactly zero didn't work because the background in e.g. T1 images can be a little off zero) and which are contiguous with the end (to avoid masking areas inside the brain that happen to be zero, eg. ventricles)

**Comment by janfreyberg** [comment]
Let me know if you have ideas for improving it, as well - I just round values, and if the rounded value is zero, and in a cluster of other zeros that touches the edge of the image at any point, it gets removed.

There could be better ways of doing it - and I'm not sure how well this would work if one was for example looking at a Z-score map...

**Comment by lukassnoek** [comment]
Ah, I didn't know some T1s have non-zero values in the background. Rounding, though, is probably not ideal either, since some statistic-maps (like $R^2$ maps) are by definition <1. But looks like a working solution for now!

**Comment by janfreyberg** [comment]
Yes, I agree - it's not ideal! I'd like to have a smarter detection algorithm in there. Will keep thinking about it...
